FROM runpod/worker-v1-vllm:v2.13.1

ENV MODEL_NAME="ibm-granite/granite-docling-258M"
ENV MODEL_REVISION="untied"
ENV OPENAI_SERVED_MODEL_NAME_OVERRIDE="granite-docling-258M"

ENV GPU_MEMORY_UTILIZATION=0.90
ENV MAX_MODEL_LEN=4096
ENV DTYPE="auto"

ENV MAX_CONCURRENCY=2
ENV DEFAULT_BATCH_SIZE=1
